/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenticCodingRouteImport } from './routes/agentic-coding'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as TechStackRouteImport } from './routes/tech-stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticCodingRoute = AgenticCodingRouteImport.update({
  id: '/agentic-coding',
  path: '/agentic-coding',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const TechStackRoute = TechStackRouteImport.update({
  id: '/tech-stack',
  path: '/tech-stack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentic-coding': typeof AgenticCodingRoute
  '/get-started': typeof GetStartedRoute
  '/tech-stack': typeof TechStackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentic-coding': typeof AgenticCodingRoute
  '/get-started': typeof GetStartedRoute
  '/tech-stack': typeof TechStackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentic-coding': typeof AgenticCodingRoute
  '/get-started': typeof GetStartedRoute
  '/tech-stack': typeof TechStackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agentic-coding' | '/get-started' | '/tech-stack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agentic-coding' | '/get-started' | '/tech-stack'
  id: '__root__' | '/' | '/agentic-coding' | '/get-started' | '/tech-stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenticCodingRoute: typeof AgenticCodingRoute
  GetStartedRoute: typeof GetStartedRoute
  TechStackRoute: typeof TechStackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-coding': {
      id: '/agentic-coding'
      path: '/agentic-coding'
      fullPath: '/agentic-coding'
      preLoaderRoute: typeof AgenticCodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-stack': {
      id: '/tech-stack'
      path: '/tech-stack'
      fullPath: '/tech-stack'
      preLoaderRoute: typeof TechStackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenticCodingRoute: AgenticCodingRoute,
  GetStartedRoute: GetStartedRoute,
  TechStackRoute: TechStackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
