/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appAppRouteImport } from './routes/(app)/_app'
import { Route as marketingMarketingRouteImport } from './routes/(marketing)/_marketing'
import { Route as marketingMarketingIndexRouteImport } from './routes/(marketing)/_marketing/index'
import { Route as appAppPokemonIndexRouteImport } from './routes/(app)/_app/pokemon/index'
import { Route as appAppPokemonNameRouteImport } from './routes/(app)/_app/pokemon/$name'

const appAppRoute = appAppRouteImport.update({
  id: '/(app)/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingRoute = marketingMarketingRouteImport.update({
  id: '/(marketing)/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingIndexRoute = marketingMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingMarketingRoute,
} as any)
const appAppPokemonIndexRoute = appAppPokemonIndexRouteImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => appAppRoute,
} as any)
const appAppPokemonNameRoute = appAppPokemonNameRouteImport.update({
  id: '/pokemon/$name',
  path: '/pokemon/$name',
  getParentRoute: () => appAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingMarketingIndexRoute
  '/pokemon/$name': typeof appAppPokemonNameRoute
  '/pokemon/': typeof appAppPokemonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingMarketingIndexRoute
  '/pokemon/$name': typeof appAppPokemonNameRoute
  '/pokemon': typeof appAppPokemonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_app': typeof appAppRouteWithChildren
  '/(marketing)/_marketing': typeof marketingMarketingRouteWithChildren
  '/(marketing)/_marketing/': typeof marketingMarketingIndexRoute
  '/(app)/_app/pokemon/$name': typeof appAppPokemonNameRoute
  '/(app)/_app/pokemon/': typeof appAppPokemonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemon/$name' | '/pokemon/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemon/$name' | '/pokemon'
  id:
    | '__root__'
    | '/(app)/_app'
    | '/(marketing)/_marketing'
    | '/(marketing)/_marketing/'
    | '/(app)/_app/pokemon/$name'
    | '/(app)/_app/pokemon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
  marketingMarketingRoute: typeof marketingMarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing': {
      id: '/(marketing)/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing/': {
      id: '/(marketing)/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingMarketingIndexRouteImport
      parentRoute: typeof marketingMarketingRoute
    }
    '/(app)/_app/pokemon/': {
      id: '/(app)/_app/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof appAppPokemonIndexRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/pokemon/$name': {
      id: '/(app)/_app/pokemon/$name'
      path: '/pokemon/$name'
      fullPath: '/pokemon/$name'
      preLoaderRoute: typeof appAppPokemonNameRouteImport
      parentRoute: typeof appAppRoute
    }
  }
}

interface appAppRouteChildren {
  appAppPokemonNameRoute: typeof appAppPokemonNameRoute
  appAppPokemonIndexRoute: typeof appAppPokemonIndexRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppPokemonNameRoute: appAppPokemonNameRoute,
  appAppPokemonIndexRoute: appAppPokemonIndexRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface marketingMarketingRouteChildren {
  marketingMarketingIndexRoute: typeof marketingMarketingIndexRoute
}

const marketingMarketingRouteChildren: marketingMarketingRouteChildren = {
  marketingMarketingIndexRoute: marketingMarketingIndexRoute,
}

const marketingMarketingRouteWithChildren =
  marketingMarketingRoute._addFileChildren(marketingMarketingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
  marketingMarketingRoute: marketingMarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
